### ISSUE TITLE
A few problems and workarounds

### ISSUE THREAD

**Issue by yatara-visuals** [yumataesu/lightScattering#3]
Hi, 
Thanks a lot for this godray shader and example! so it took me a quite few hours to get it working (i started OF only weeks ago) and i had a few problems in the end which I would like to share the solutions of:

- For some reason, when moving the camera up and down, the rays source moved up when the light source moved down (and vice versa). Solution : I changed one line in lightScattering.vert like so
`v_texcoord = vec2(texcoord.x, 1-0-texcoord.y);`

- When rotating the camera 180 degrees from the light source, I had rays comming out of the middle of the screen, because even thought the source was in the back, it was technicaly in the center of the screen in screen coordinates. Solution : I added this condition before the launching the godray shader.
`if (cam.worldToScreen(sun.getPosition()).z < 1){
[godray shader stuff]
}`

These might not be the most elegant solutions but they worked for me so maybe they'll be usefull to someone else.

**Comment by yumataesu** [comment]
thank you very much!!!!!
I added yours.
